apiVersion: stash.appscode.com/v1alpha1
kind: Repository
metadata:
  name: hello-repo
  namespace: demo
spec:
  backend:
    gcs:
      bucket: kubedb-qa
      prefix: hello-prefix
    storageSecretName: gcs-secret

---
apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
metadata:
  name: mysql-backup-config
  namespace: demo
spec:
  runtimeSettings:
    pod:
      serviceAccountName: mysql-backup-restore
#  schedule: "* * * * *"
  task:
    name: mysql-backup-task
  repository:
    name: hello-repo
  target:
    ref:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: mysql-quickstart
  retentionPolicy:
    keepLast: 5
    prune: true
---
apiVersion: stash.appscode.com/v1beta1
kind: BackupSession
metadata:
  name: mysql-backup-01
  namespace: demo
spec:
  backupConfiguration:
    name: mysql-backup-config
