// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: test.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestHelloWorld struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hello         string                 `protobuf:"bytes,1,opt,name=hello,proto3" json:"hello,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestHelloWorld) Reset() {
	*x = RequestHelloWorld{}
	mi := &file_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestHelloWorld) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestHelloWorld) ProtoMessage() {}

func (x *RequestHelloWorld) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestHelloWorld.ProtoReflect.Descriptor instead.
func (*RequestHelloWorld) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{0}
}

func (x *RequestHelloWorld) GetHello() string {
	if x != nil {
		return x.Hello
	}
	return ""
}

type ResponseHelloWorld struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	World         string                 `protobuf:"bytes,1,opt,name=world,proto3" json:"world,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseHelloWorld) Reset() {
	*x = ResponseHelloWorld{}
	mi := &file_test_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseHelloWorld) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseHelloWorld) ProtoMessage() {}

func (x *ResponseHelloWorld) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseHelloWorld.ProtoReflect.Descriptor instead.
func (*ResponseHelloWorld) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseHelloWorld) GetWorld() string {
	if x != nil {
		return x.World
	}
	return ""
}

var File_test_proto protoreflect.FileDescriptor

const file_test_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"test.proto\x12\x05proto\")\n" +
	"\x11RequestHelloWorld\x12\x14\n" +
	"\x05hello\x18\x01 \x01(\tR\x05hello\"*\n" +
	"\x12ResponseHelloWorld\x12\x14\n" +
	"\x05world\x18\x01 \x01(\tR\x05world2V\n" +
	"\x11HelloWorldService\x12A\n" +
	"\bSayHello\x12\x18.proto.RequestHelloWorld\x1a\x19.proto.ResponseHelloWorld\"\x00B\vZ\tpkg/protob\x06proto3"

var (
	file_test_proto_rawDescOnce sync.Once
	file_test_proto_rawDescData []byte
)

func file_test_proto_rawDescGZIP() []byte {
	file_test_proto_rawDescOnce.Do(func() {
		file_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_proto_rawDesc), len(file_test_proto_rawDesc)))
	})
	return file_test_proto_rawDescData
}

var file_test_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_test_proto_goTypes = []any{
	(*RequestHelloWorld)(nil),  // 0: proto.RequestHelloWorld
	(*ResponseHelloWorld)(nil), // 1: proto.ResponseHelloWorld
}
var file_test_proto_depIdxs = []int32{
	0, // 0: proto.HelloWorldService.SayHello:input_type -> proto.RequestHelloWorld
	1, // 1: proto.HelloWorldService.SayHello:output_type -> proto.ResponseHelloWorld
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_test_proto_init() }
func file_test_proto_init() {
	if File_test_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_proto_rawDesc), len(file_test_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_test_proto_goTypes,
		DependencyIndexes: file_test_proto_depIdxs,
		MessageInfos:      file_test_proto_msgTypes,
	}.Build()
	File_test_proto = out.File
	file_test_proto_goTypes = nil
	file_test_proto_depIdxs = nil
}
