name: CI

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.4'  # Set the Go version you're using
      - name: Install golangci-lint
        run: |
          curl -sSfL https://github.com/golangci/golangci-lint/releases/download/v1.52.0/golangci-lint-1.52.0-linux-amd64.tar.gz | tar -xz -C /tmp
          sudo mv /tmp/golangci-lint-1.52.0-linux-amd64/golangci-lint /usr/local/bin
      - name: Run golangci-lint
        run: golangci-lint run
      - name: Run go fmt
        run: |
          unformatted=$(go fmt ./...)
          if [ -n "$unformatted" ]; then
            echo "Go files need formatting:"
            echo "$unformatted"
            exit 1
          else
            echo "All Go files are formatted."
          fi
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

