name: Release

on:
  push:
    tags:
      - "*.*"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Debug GitHub Token
        run: echo "GITHUB_TOKEN is available"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry (GHCR)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo $GITHUB_TOKEN | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Build and tag Docker image
        env:
          IMAGE_NAME: ghcr.io/sheikh-arman/go-project
        run: |
          TAG=${GITHUB_REF#refs/tags/}  # Extracts the tag name from 'refs/tags/x.y.z'
          echo "Using tag: $TAG"
          docker build -t $IMAGE_NAME:$TAG .
          docker tag $IMAGE_NAME:$TAG $IMAGE_NAME:latest

      - name: Push Docker image to GHCR
        env:
          IMAGE_NAME: ghcr.io/sheikh-arman/go-project
        run: |
          TAG=${GITHUB_REF#refs/tags/}  # Extracts the tag name from 'refs/tags/x.y.z'
          docker push $IMAGE_NAME:$TAG
          docker push $IMAGE_NAME:latest
